// <auto-generated />
namespace Tickets_Bus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adding_mfa_fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_mfa_fields));
        
        string IMigrationMetadata.Id
        {
            get { return "201706050857560_adding_mfa_fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
