//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Tickets_Bus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BUS()
        {
            this.Drivers = new HashSet<Driver>();
        }

        [Display(Name = "Код атобуса")]
        public int ID_Bus { get; set; }
        [Display(Name = "Назва атобуса")]
        public string Name_Bus { get; set; }
        [Display(Name = "Номер атобуса")]
        public string Number_Bus { get; set; }
        [Display(Name = "Кількість місць")]
        public int Num_Seats { get; set; }
        [Display(Name = "Дата ТО")]
        public System.DateTime Date_LastTO { get; set; }
        [Display(Name = "Надійність")]
        public string Reliability { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Driver> Drivers { get; set; }
    }
}
