//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets_Bus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route_()
        {
            this.Route_Station = new HashSet<Route_Station>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int ID_Route { get; set; }
        public int Departure { get; set; }
        public int Arrival { get; set; }
        public TimeSpan Date_departure { get; set; }
        public TimeSpan Date_arrival { get; set; }
        public int ID_Driver { get; set; }
        public DateTime DateArrival { get; set; }

        public virtual Driver Driver { get; set; }
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Route_Station> Route_Station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
