//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets_Bus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID_Ticket { get; set; }
        public int ID_Route { get; set; }
        public int Departure { get; set; }
        public int Arrival { get; set; }
        public int Numb_Seat { get; set; }
        public double Price { get; set; }
        public string Name_Surname { get; set; }
        public string Name_Surnames { get; set; }
        public System.DateTime Date_Sale { get; set; }
    
        public virtual Route_ Route_ { get; set; }
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
    }
}
